extensions:
  file_storage:
    directory: /var/lib/otelcol/file_storage
    timeout: 1s

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp:
    endpoint: ${env:OTEL_EXPORTER_OTLP_BACKEND_ENDPOINT}
    tls:
      insecure: true
    sending_queue:
      enabled: true
      storage: file_storage
      num_consumers: 4
      queue_size: 10000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 0s

service:
  extensions:
    - file_storage
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp
